""" trigger/02000245_bf/trigger_03_02.xml """
import trigger_api


class 대기(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_mesh(trigger_ids=[801], visible=True)
        self.set_skill(trigger_ids=[7001], enable=True)
        self.set_skill(trigger_ids=[7002], enable=True)
        self.set_skill(trigger_ids=[7003], enable=True)
        self.set_skill(trigger_ids=[7004], enable=True)
        self.set_skill(trigger_ids=[7005], enable=True)
        self.set_skill(trigger_ids=[7006], enable=True)
        self.set_skill(trigger_ids=[7007], enable=True)
        self.set_skill(trigger_ids=[7008], enable=True)
        self.set_skill(trigger_ids=[7009], enable=True)
        self.set_skill(trigger_ids=[7010], enable=True)
        self.set_skill(trigger_ids=[7011], enable=True)
        self.set_skill(trigger_ids=[7012], enable=True)
        self.set_skill(trigger_ids=[7013], enable=True)
        self.set_skill(trigger_ids=[7014], enable=True)
        self.set_skill(trigger_ids=[7015], enable=True)
        self.set_skill(trigger_ids=[7016], enable=True)
        self.set_skill(trigger_ids=[7017], enable=True)
        self.set_skill(trigger_ids=[7018], enable=True)
        self.set_skill(trigger_ids=[7019], enable=True)
        self.set_skill(trigger_ids=[7020], enable=True)
        self.set_effect(trigger_ids=[901], visible=True)
        self.set_effect(trigger_ids=[902], visible=True)
        self.set_effect(trigger_ids=[903], visible=True)
        self.set_effect(trigger_ids=[904], visible=True)
        self.set_effect(trigger_ids=[905], visible=True)
        self.set_effect(trigger_ids=[906], visible=True)
        self.set_effect(trigger_ids=[907], visible=True)
        self.set_effect(trigger_ids=[908], visible=True)
        self.set_effect(trigger_ids=[909], visible=True)
        self.set_effect(trigger_ids=[910], visible=True)
        self.set_effect(trigger_ids=[911], visible=True)
        self.set_effect(trigger_ids=[912], visible=True)
        self.set_effect(trigger_ids=[913], visible=True)
        self.set_effect(trigger_ids=[914], visible=True)
        self.set_effect(trigger_ids=[915], visible=True)
        self.set_effect(trigger_ids=[916], visible=True)
        self.set_effect(trigger_ids=[917], visible=True)
        self.set_effect(trigger_ids=[918], visible=True)
        self.set_effect(trigger_ids=[919], visible=True)
        self.set_effect(trigger_ids=[920], visible=True)

    def on_tick(self) -> trigger_api.Trigger:
        if self.user_detected(box_ids=[207]):
            return 단계1(self.ctx)


class 단계1(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_mesh(trigger_ids=[801])
        self.set_skill(trigger_ids=[7001])
        self.set_skill(trigger_ids=[7002])
        self.set_skill(trigger_ids=[7003])
        self.set_skill(trigger_ids=[7004])
        self.set_skill(trigger_ids=[7005])
        self.set_skill(trigger_ids=[7006])
        self.set_skill(trigger_ids=[7007])
        self.set_skill(trigger_ids=[7008])
        self.set_skill(trigger_ids=[7009])
        self.set_skill(trigger_ids=[7010])
        self.set_skill(trigger_ids=[7011])
        self.set_skill(trigger_ids=[7012])
        self.set_skill(trigger_ids=[7013])
        self.set_skill(trigger_ids=[7014])
        self.set_skill(trigger_ids=[7015])
        self.set_skill(trigger_ids=[7016])
        self.set_skill(trigger_ids=[7017])
        self.set_skill(trigger_ids=[7018])
        self.set_skill(trigger_ids=[7019])
        self.set_skill(trigger_ids=[7020])
        self.set_effect(trigger_ids=[901])
        self.set_effect(trigger_ids=[902])
        self.set_effect(trigger_ids=[903])
        self.set_effect(trigger_ids=[904])
        self.set_effect(trigger_ids=[905])
        self.set_effect(trigger_ids=[906])
        self.set_effect(trigger_ids=[907])
        self.set_effect(trigger_ids=[908])
        self.set_effect(trigger_ids=[909])
        self.set_effect(trigger_ids=[910])
        self.set_effect(trigger_ids=[911])
        self.set_effect(trigger_ids=[912])
        self.set_effect(trigger_ids=[913])
        self.set_effect(trigger_ids=[914])
        self.set_effect(trigger_ids=[915])
        self.set_effect(trigger_ids=[916])
        self.set_effect(trigger_ids=[917])
        self.set_effect(trigger_ids=[918])
        self.set_effect(trigger_ids=[919])
        self.set_effect(trigger_ids=[920])


initial_state = 대기
